export const colors = {
  light: {
    background: '#FEFDF5',
    foreground: '#1c1c1e',
    card: '#ffffff',
    cardForeground: '#1c1c1e',
    primary: '#000000',
    primaryForeground: '#ffffff',
    secondary: '#F7F6F0',
    secondaryForeground: '#1c1c1e',
    muted: '#F7F6F0',
    mutedForeground: '#8e8e93',
    accent: '#F7F6F0',
    accentForeground: '#1c1c1e',
    destructive: '#ff3b30',
    border: '#d1d1d6',
  },
  dark: {
    background: '#000000',
    foreground: '#ffffff',
    card: '#1c1c1e',
    cardForeground: '#ffffff',
    primary: '#ffffff',
    primaryForeground: '#000000',
    secondary: '#2c2c2e',
    secondaryForeground: '#ffffff',
    muted: '#2c2c2e',
    mutedForeground: '#8e8e93',
    accent: '#2c2c2e',
    accentForeground: '#ffffff',
    destructive: '#ff453a',
    border: '#38383a',
  },
};
